"""add blacklist

Revision ID: 50602804ec4f
Revises: 62793c1ea8db
Create Date: 2018-11-26 08:56:33.914313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50602804ec4f'
down_revision = '62793c1ea8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['users.id'], name=op.f('fk_blacklist_block_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blacklist_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist')
    # ### end Alembic commands ###
