"""user add tokens

Revision ID: 807a5f3cfd23
Revises: fe9d9ed0b2e9
Create Date: 2018-11-01 23:30:28.602978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807a5f3cfd23'
down_revision = 'fe9d9ed0b2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
