"""followers table add timestamp

Revision ID: b7fa03819d57
Revises: 1e179ce09b5b
Create Date: 2018-11-12 22:04:30.807076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7fa03819d57'
down_revision = '1e179ce09b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'timestamp')
    # ### end Alembic commands ###
